default: &default
  adapter: sqlserver
  host: <%= ENV.fetch("POR_DB_HOST") %>
  port: <%= ENV.fetch("POR_DB_PORT") %>
  username: <%= ENV.fetch("POR_DB_USERNAME") %>
  password: <%= ENV.fetch("POR_DB_PASSWORD") %>
  database: POR
  azure: false
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

postgres_default: &postgres_default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
  secondary:
    <<: *postgres_default
    database: betren_app_development
  cable:
    <<: *postgres_default
    database: betren_app_development_cable
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
  secondary:
    <<: *postgres_default
    database: betren_app_test

production:
  primary:
    <<: *default
  secondary:
    <<: *postgres_default
    url: <%= ENV['DATABASE_URL'] %>
  cable:
    <<: *postgres_default
    url: <%= ENV['CABLE_DATABASE_URL'] %>
    migrations_paths: db/cable_migrate
